variable "location" {
  type        = string
  description = <<DESCRIPTION
Azure region where all resources should be deployed.

This specifies the primary Azure region for deploying the AI/ML landing zone infrastructure. All resources will be created in this region unless specifically configured otherwise in individual resource definitions.
DESCRIPTION
  nullable    = false
}

# This is required for most resource modules
variable "resource_group_name" {
  type        = string
  description = <<DESCRIPTION
The name of the resource group where all resources will be deployed.

This resource group will contain all the AI/ML landing zone infrastructure components. The module always creates this resource group, so it must not already exist unless it is first imported into Terraform state.
DESCRIPTION
}

variable "enable_telemetry" {
  type        = bool
  default     = true
  description = <<DESCRIPTION
This variable controls whether or not telemetry is enabled for the module.
For more information see <https://aka.ms/avm/telemetryinfo>.
If it is set to false, then no telemetry will be collected.
DESCRIPTION
  nullable    = false
}

variable "flag_platform_landing_zone" {
  type        = bool
  default     = true
  description = <<DESCRIPTION
Flag to indicate if the platform landing zone is enabled.

If set to true, the module will deploy resources and connect to a platform landing zone hub. This enables integration with existing hub-and-spoke network architectures and centralized management services.
DESCRIPTION
}

variable "ignore_body_changes" {
  type = object({
    apimanagement_service_apis                           = optional(list(string), [])
    apimanagement_service_apis_operations                = optional(list(string), [])
    apimanagement_service_apis_policies                  = optional(list(string), [])
    apimanagement_service_backends                       = optional(list(string), [])
    authorization_role_assignments                       = optional(list(string), [])
    bing_accounts                                        = optional(list(string), [])
    network_network_security_groups_security_rules       = optional(list(string), [])
    network_virtual_hubs_hub_virtual_network_connections = optional(list(string), [])
    resources_resource_groups                            = optional(list(string), [])
  })
  default     = {}
  description = <<DESCRIPTION
Body-relative dot-notation paths to ignore for each AzAPI resource. Ignored configuration is not sent to Azure, and changes to these paths take effect only after apply.

- `apimanagement_service_apis` - Paths ignored on API Management APIs.
- `apimanagement_service_apis_operations` - Paths ignored on API Management API operations.
- `apimanagement_service_apis_policies` - Paths ignored on API Management API policies.
- `apimanagement_service_backends` - Paths ignored on API Management backends.
- `authorization_role_assignments` - Paths ignored on role assignments.
- `bing_accounts` - Paths ignored on Bing accounts.
- `network_network_security_groups_security_rules` - Paths ignored on network security rules.
- `network_virtual_hubs_hub_virtual_network_connections` - Paths ignored on virtual hub connections.
- `resources_resource_groups` - Paths ignored on resource groups.
DESCRIPTION
  nullable    = false
}

variable "name_prefix" {
  type        = string
  default     = null
  description = <<DESCRIPTION
Optional prefix to be used for naming resources.

This prefix will be applied to all resource names generated by the module. It is useful for ensuring consistent naming conventions across deployments without requiring explicit names for each resource. The prefix should be kept under 10 characters and use only alphanumeric lowercase characters to avoid Azure naming limitations.
DESCRIPTION

  validation {
    condition = var.name_prefix == null || (
      length(var.name_prefix) <= 10 &&
      can(regex("^[a-z0-9]+$", var.name_prefix))
    )
    error_message = "The name_prefix must contain only lowercase alphanumeric characters and be 10 characters or less or remain null."
  }
}

variable "resource_types" {
  type = object({
    apimanagement_service_apis                                   = optional(string, "Microsoft.ApiManagement/service/apis@2024-05-01")
    apimanagement_service_apis_operations                        = optional(string, "Microsoft.ApiManagement/service/apis/operations@2024-05-01")
    apimanagement_service_apis_policies                          = optional(string, "Microsoft.ApiManagement/service/apis/policies@2024-05-01")
    apimanagement_service_backends                               = optional(string, "Microsoft.ApiManagement/service/backends@2024-05-01")
    authorization_role_assignments                               = optional(string, "Microsoft.Authorization/roleAssignments@2022-04-01")
    bing_accounts                                                = optional(string, "Microsoft.Bing/accounts@2025-05-01-preview")
    cognitiveservices_locations_resource_groups_deleted_accounts = optional(string, "Microsoft.CognitiveServices/locations/resourceGroups/deletedAccounts@2021-04-30")
    network_network_security_groups_security_rules               = optional(string, "Microsoft.Network/networkSecurityGroups/securityRules@2024-05-01")
    network_virtual_hubs_hub_virtual_network_connections         = optional(string, "Microsoft.Network/virtualHubs/hubVirtualNetworkConnections@2024-05-01")
    resources_resource_groups                                    = optional(string, "Microsoft.Resources/resourceGroups@2024-11-01")
  })
  default     = {}
  description = <<DESCRIPTION
AzAPI resource types and API versions used by this module.

- `apimanagement_service_apis` - API Management API resource type.
- `apimanagement_service_apis_operations` - API Management API operation resource type.
- `apimanagement_service_apis_policies` - API Management API policy resource type.
- `apimanagement_service_backends` - API Management backend resource type.
- `authorization_role_assignments` - Role assignment resource type.
- `bing_accounts` - Bing account resource type.
- `cognitiveservices_locations_resource_groups_deleted_accounts` - Deleted Cognitive Services account action type.
- `network_network_security_groups_security_rules` - Network security rule resource type.
- `network_virtual_hubs_hub_virtual_network_connections` - Virtual hub connection resource type.
- `resources_resource_groups` - Resource group resource type.
DESCRIPTION
  nullable    = false
}

variable "retry" {
  type = object({
    error_message_regex  = optional(list(string))
    interval_seconds     = optional(number)
    max_interval_seconds = optional(number)
  })
  default     = null
  description = <<DESCRIPTION
Retry configuration applied to every supported AzAPI resource declared by this module.

- `error_message_regex` - Regular expressions matching errors that should be retried.
- `interval_seconds` - Initial interval in seconds between retries.
- `max_interval_seconds` - Maximum interval in seconds between retries.
DESCRIPTION
}

variable "tags" {
  type        = map(string)
  default     = null
  description = <<DESCRIPTION
Map of tags to be assigned to all resources created by this module.

Tags are key-value pairs that help organize and manage Azure resources. These tags will be applied to all resources created by the module, enabling consistent resource governance, cost tracking, and operational management across the AI/ML landing zone infrastructure.
DESCRIPTION
}

variable "timeouts" {
  type = object({
    create = optional(string)
    read   = optional(string)
    update = optional(string)
    delete = optional(string)
  })
  default     = null
  description = <<DESCRIPTION
Default per-operation timeouts applied to every supported AzAPI resource declared by this module.

- `create` - Timeout for create operations.
- `read` - Timeout for read operations.
- `update` - Timeout for update operations.
- `delete` - Timeout for delete operations.
DESCRIPTION
}
