variable "deployer_ip_address" {
  type        = string
  description = "The Ip address of the compute resource deploying the module. This is used to allow access Key vault for the jump box secrets."
}

variable "location" {
  type        = string
  description = <<DESCRIPTION
Azure region where all resources should be deployed.

This specifies the primary Azure region for deploying the AI/ML landing zone infrastructure. All resources will be created in this region unless specifically configured otherwise in individual resource definitions.
DESCRIPTION
  nullable    = false
}

# This is required for most resource modules
variable "resource_group_name" {
  type        = string
  description = <<DESCRIPTION
The name of the resource group where all resources will be deployed.

This resource group will contain all the AI/ML landing zone infrastructure components. The resource group should already exist or will be created as part of the deployment process.
DESCRIPTION
}

variable "vnet_definition" {
  type = object({
    name          = optional(string)
    address_space = string
  })
  description = <<DESCRIPTION
Configuration object for the Virtual Network (VNet) to be deployed.

- `name` - (Optional) The name of the Virtual Network. If not provided, a name will be generated.
- `address_space` - (Required) The address space for the Virtual Network in CIDR notation.
DESCRIPTION
}

variable "enable_telemetry" {
  type        = bool
  default     = true
  description = <<DESCRIPTION
This variable controls whether or not telemetry is enabled for the module.
For more information see <https://aka.ms/avm/telemetryinfo>.
If it is set to false, then no telemetry will be collected.
DESCRIPTION
  nullable    = false
}

variable "jump_vm_definition" {
  type = object({
    name             = optional(string)
    sku              = optional(string, "Standard_B2s")
    tags             = optional(map(string))
    enable_telemetry = optional(bool, true)
  })
  default     = {}
  description = <<DESCRIPTION
Configuration object for the Build VM to be created for managing the implementation services.

- `name` - (Optional) The name of the Build VM. If not provided, a name will be generated.
- `sku` - (Optional) The VM size/SKU for the Build VM. Default is "Standard_B2s".
- `tags` - (Optional) Map of tags to assign to the Build VM.
- `enable_telemetry` - (Optional) Whether telemetry is enabled for the Build VM module. Default is true.
DESCRIPTION
}

variable "name_prefix" {
  #TODO: add a validation rule to keep this under 10 characters only alphanumeric lowercase
  type        = string
  default     = null
  description = <<DESCRIPTION
Optional prefix to be used for naming resources.

This prefix will be applied to all resource names generated by the module. It is useful for ensuring consistent naming conventions across deployments without requiring explicit names for each resource. The prefix should be kept under 10 characters and use only alphanumeric lowercase characters to avoid Azure naming limitations.
DESCRIPTION
}

variable "tags" {
  type        = map(string)
  default     = null
  description = <<DESCRIPTION
Map of tags to be assigned to all resources created by this module.

Tags are key-value pairs that help organize and manage Azure resources. These tags will be applied to all resources created by the module, enabling consistent resource governance, cost tracking, and operational management across the AI/ML landing zone infrastructure.
DESCRIPTION
}

variable "resource_types" {
  type = object({
    network_bastion_hosts     = optional(string, "Microsoft.Network/bastionHosts@2024-05-01")
    resources_resource_groups = optional(string, "Microsoft.Resources/resourceGroups@2024-11-01")
  })
  default     = {}
  nullable    = false
  description = <<DESCRIPTION
AzAPI resource types and API versions used by this module.

- `network_bastion_hosts` - Bastion host resource type.
- `resources_resource_groups` - Resource group resource type.
DESCRIPTION
}

variable "retry" {
  type = object({
    error_message_regex  = optional(list(string))
    interval_seconds     = optional(number)
    max_interval_seconds = optional(number)
  })
  default     = null
  description = <<DESCRIPTION
Retry configuration applied to every supported AzAPI resource declared by this module.

- `error_message_regex` - Regular expressions matching errors that should be retried.
- `interval_seconds` - Initial interval in seconds between retries.
- `max_interval_seconds` - Maximum interval in seconds between retries.
DESCRIPTION
}

variable "timeouts" {
  type = object({
    create = optional(string)
    read   = optional(string)
    update = optional(string)
    delete = optional(string)
  })
  default     = null
  description = <<DESCRIPTION
Default per-operation timeouts applied to every supported AzAPI resource declared by this module.

- `create` - Timeout for create operations.
- `read` - Timeout for read operations.
- `update` - Timeout for update operations.
- `delete` - Timeout for delete operations.
DESCRIPTION
}

variable "ignore_body_changes" {
  type = object({
    network_bastion_hosts     = optional(list(string), [])
    resources_resource_groups = optional(list(string), [])
  })
  default     = {}
  nullable    = false
  description = <<DESCRIPTION
Body-relative dot-notation paths to ignore for each AzAPI resource. Ignored configuration is not sent to Azure, and changes to these paths take effect only after apply.

- `network_bastion_hosts` - Paths ignored on the Bastion host.
- `resources_resource_groups` - Paths ignored on the resource group.
DESCRIPTION
}
